- slug: constitucion-politica-de-la-republica-de-chile
  id_norma: 242302
  note: Constitución Política de la República de Chile
- slug: codigo-civil
  id_norma: 172986
  note: Código Civil
- slug: codigo-penal
  id_norma: 1984
  note: Código Penal
- slug: codigo-del-trabajo
  id_norma: 207436
  note: Código del Trabajo
- slug: codigo-de-comercio
  id_norma: 1974
  note: Código de Comercio
- slug: codigo-tributario
  id_norma: 6374
  note: Código Tributario
- slug: codigo-de-procedimiento-civil
  id_norma: 22740
  note: Código de Procedimiento Civil
- slug: codigo-procesal-penal
  id_norma: 176595
  note: Código Procesal Penal
- slug: codigo-organico-de-tribunales
  id_norma: 25563
  note: Código Orgánico de Tribunales
- slug: codigo-de-aguas
  id_norma: 5605
  note: Código de Aguas
- slug: codigo-de-mineria
  id_norma: 29668
  note: Código de Minería
- slug: codigo-aeronautico
  id_norma: 30287
  note: Código Aeronáutico
- slug: codigo-sanitario
  id_norma: 5595
  note: Código Sanitario
- slug: codigo-de-justicia-militar
  id_norma: 18914
  note: Código de Justicia Militar
- slug: codigo-de-derecho-internacional-privado
  id_norma: 12820
  note: Código de Derecho Internacional Privado
- slug: codigo-de-procedimiento-penal
  id_norma: 22960
  note: Código de Procedimiento Penal
